### ISSUE TITLE
Error: Variable res.not_found_header not found in context while rendering partials/404.html

### ISSUE THREAD

**Issue by famfop** [thomasweitzel/zolarwind#5]
Hi, I am trying out zola and liked your theme. I am unfortunately unable to get it working.

Following the [official instructions](https://www.getzola.org/documentation/themes/installing-and-using-themes/) I pulled your repository into a `themes/zolarwind` folder and configured my `config.toml` to use

```
default_language = "de" # (tried out "en" as well)
theme = "zolarwind"
[...]
[extra]
path_language_resources = "themes/zolarwind/i18n/"
```
Running `zola serve` fails with
```
Error: Failed to serve the site
Error: Failed to render '404.html'
Error: Reason: Variable `res.not_found_header` not found in context while rendering 'partials/404.html'
```
Which I am unable to explain. As far as I understand the `base.html` template sets the `res` variable to use `config.extra.path_language_resource` which should be correctly set by my `config.toml`. 

Do you have any idea what I could be missing?

**Comment by thomasweitzel** [comment]
The path to the language resource files in the configuration `path_language_resources` seems to be set correctly, and I assume you have set all the other non-optional configuration variables in `config.toml` as mentioned in the [documentation](https://github.com/thomasweitzel/zolarwind/blob/main/README.md#configuration).

If the resource file could not be found at all, you would see an error message like `"load_data": themes/zolarwind/i18n/de.toml doesn't exist` or something similar. Since you're not seeing this, it means the resource file can be accessed.

Therefore, I assume that the key `not_found_header` is not present in the resource file you are using. It might be corrupted. How does your `themes/zolarwind/i18n/de.toml` look? Is it the original file?

I'm interested in fixing this issue if it's a bug in Zolarwind. Could you provide a ZIP archive of your stripped-down project so I can reproduce the problem?

**Comment by thomasweitzel** [comment]
Hi!
Just a friendly reminder about this issue. I'm still looking forward to your feedback and suggestions. If you have any updates or thoughts, please share them here. Thank you!

**Comment by famfop** [comment]
Hi, I am sorry, I was away for a few days. I am attaching the tar of my testproject. I believe I only went through the "getting started" steps on the zola website and then tried adding your project as a theme.
[testproj.zip](https://github.com/user-attachments/files/16040086/testproj.zip)

**Comment by thomasweitzel** [comment]
Zolarwind is a somewhat opinionated theme. It requires some configuration values to be present im the `config.toml` and the pages and posts frontmatter. I highly recommend reading the [documentation](https://github.com/thomasweitzel/zolarwind/tree/main?tab=readme-ov-file).

It's best to check out the project from Github and start it stand-alone with `zola serve`.
The current version requires at least Zola 0.19.0, because there were some breaking changes from 0.18.0 to 0.19.0 (yes, I'm looking at you `generate_feed` etc.).
Then follow the [guide](https://github.com/thomasweitzel/zolarwind/tree/main?tab=readme-ov-file#integrating-in-theme-folder) on how to integrate it into your own `theme` folder.

If you want to adjust your project to work with Zolarwind, here are the minimum requirements you need to satisfy:

- read [this](https://github.com/thomasweitzel/zolarwind/tree/main?tab=readme-ov-file#integrating-in-theme-folder) on how to integrate Zolarwind into your project; at least, you have to move the folder (contents) of `/themes/zolarwind/static/css` to /`static/css`
- you have your own templates in `/templates`, that are used and override some Zolarwind templates; it's best to remove them
- in your `/content/blog/_index.md` directory, you reference at least one of your own templates:
  ```
  +++
  title = "List of blog posts"
  sort_by = "date"
  template = "blog.html"
  page_template = "blog-page.html" # HERE!
  +++
  ```
  Use this instead (see `/themes/zolarwind/content/blog/_index.md`):
  ```
  +++
  template = "blog.html"
  page_template = "blog-post.html"
  paginate_by = 6
  sort_by = "date"
  transparent = true
  +++
  ```
- read [this](https://github.com/thomasweitzel/zolarwind/tree/main?tab=readme-ov-file#configuration) on what configuration values have to be provided. You need to provide:
  - `taxonomies`, e.g.
    ```toml
    # The taxonomies to use for the site
    taxonomies = [
        { name = "tags", paginate_by = 6, feed = true},
    ]
    ```

In the `[extra]` section you have to provide (you can see `/themes/zolarwind/config.toml` for examples):
- `favicon_svg`, e.g. favicon_svg = "/img/yin-yang.svg"
- `menu_pages`, can be empty, e.g. `menu_pages = []`
- `social_links`, can be empty, e.g. `social_links = []`
- `footer_pages`, can be empty, e.g. `footer_pages = []`
- `quote_text`, can be empty, e.g. `quote.text = ""`
- `quote.author`, can be empty, e.g. `quote.author = ""`
- `site_description`, can be empty, e.g. `site_description = ""`

Your blog posts should have at least an addition `description`, but that's indeed  optional.

There need to be two `_index.md` files:
- `/content/_index.md`:
  ```
  +++
  title = "Blog of Me"
  paginate_by = 6
  sort_by = "date"
  +++
  ```
- `/content/blog/_index.md`:
  ```
  +++
  template = "blog.html"
  page_template = "blog-post.html"
  paginate_by = 6
  sort_by = "date"
  transparent = true
  +++
  ```

With these changes I was able to get your project to use Zolarwind. I hope that it will help you, too.

**Comment by thomasweitzel** [comment]
JFYI, I've made all these `[extra]` variables optional with the latest commit.

- favicon_svg
- menu_pages
- social_links
- footer_pages
- quote_text
- quote.author
- site_description

This change is also reflected in the README.md. You can now ignore these variables if you want. You don't get any warning or error messages, but you also don't have these elements on your pages anymore.

**Comment by thomasweitzel** [comment]
Hi @famfop, I wanted to check in to see if you still need help with this issue. If I don't hear back from you in the next week, I will close the issue to keep our repository tidy. Feel free to reopen it if you need further assistance. Thanks!

**Comment by famfop** [comment]
Dear @thomasweitzel I just tried out all of your changes and was indeed able to get it up and running. Thanks!

There were the following two minor changes I had do to - both in `config.toml`:
- change `generate_feed = true` to `generate_feeds = true`
- change `feed_filename = "atom.xml"` to `feed_filenames = ["atom.xml"]`

which I assume are changes due to me using `zola 0.19.1`.

Thank you for the detailed explanation, I hope this issue may find use for a "zola-novice" like me in getting started using your theme.
