### ISSUE TITLE
No images in "About"

### ISSUE THREAD

**Issue by stalkerGH** [thomasweitzel/zolarwind#7]
I'd like to add some images in "About" page. I got it in default path: `content/pages/about.md` Below text I inserted:

```
![](images/image.webp)
```

Of course `images` directory is in `content/pages/` and image.webp is inside. What should I check then?

**Comment by thomasweitzel** [comment]
You can apply the same layout for pages that is used for blog posts: group all resources for a page inside a directory. Instead of `pages/about.md`, you have the directory `pages/about/`. Inside it, you have `pages/about/index.md` (`index.md` should be the renamed `about.md`) and `pages/about/image.webp`.

As a consequence, it is easy to reference an image inside the about page (which is now the file `pages/about/index.md`): `![](image.webp)`.

This is not a Zolarwind specific thing, but is valid for Zola-based web sites in general.

**Comment by stalkerGH** [comment]
Thank you very much for detailed explanation, I got it to work :) I still learn Zola after converting from Wordpress-like thinking...
